#! /bin/bash
#pr1

url="pemula.linux.or.id";
angka=32;

printf "Hi, pake printf ala C\n\t\a di bash\n";
printf "My url %s\n %d decimal = %o octal\n" $url $angka $angka;
printf "%d decimal dalam float = %.2f\n" $angka $angka
